FROM registry-vpc.cn-beijing.aliyuncs.com/yuuyoo/openjdk:1.8
MAINTAINER dave@yuuyoo.com

COPY config-0.0.1-SNAPSHOT.jar /deployments/app.jar

ENV URL="http://127.0.0.1:8887/manage/status"
EXPOSE 8888 8887
